First commit
alexey-ershkov/Archiver_project pull request #1
Opened 2019-11-07 21:06 UTC by sanya554455

2019-11-08 13:29 UTC, leshiy1295 commented
На ревью нужно отправлять уже оформленный и готовый к нему код
Когда будете готовы - поставьте меня и напишите соответствующий комментарий

2019-11-08 21:17 UTC, sanya554455 commented
Все файлы готовы к проверке. "First commit" теперь тоже считается. Расписал архитектуру модуля, прикрепил UML, написал заголовки, подготовил тесты, поставил заглушку в одном месте,  как только начнется реализация каждого класса, сразу появятся настоящие тесты.

2019-11-13 10:13 UTC, leshiy1295 requested changes
смотреть пока особо нечего
если захотите оформить код на ревью - добавьте в качестве ревьюера снова

2019-11-13 10:13 UTC, leshiy1295 commented on gtests/TestSelection.cpp
> +#include "../Selection.cpp"
относительные include
да ещё и cpp-файлов...

2019-11-13 10:13 UTC, leshiy1295 commented on gtests/TestSelection.cpp
> +TEST(OutPutTestAboutSize, TestIsCompressionDataLessOriginal){
на РК обсудили, что стоит добавить реальные тестовые файлы

2019-11-13 10:13 UTC, leshiy1295 commented on Selection.h
> +    Huffman huffman_algorithm;
про это тоже обсудили на РК
не нужно явно здесь создавать объекты всевозможных алгоритмов

2019-11-13 10:13 UTC, leshiy1295 commented on Huffman.cpp
> +Huffman::Huffman(){
есть ключевое слово default

2019-11-13 10:13 UTC, leshiy1295 commented
Наконец, PR для ревью должны быть оформлены из Вашей ветки в основную ветку всего репозитория (которая master по умолчанию)

2019-12-01 13:29 UTC, closed without merging