Alexey ershkov
alexey-ershkov/Archiver_project pull request #3
Opened 2019-11-09 10:52 UTC by alexey-ershkov

2019-11-13 10:34 UTC, leshiy1295 commented
Для ревью нужно будет оформить Pull Request в основную ветку репозитория (master по умолчанию)

2019-11-13 13:27 UTC, alexey-ershkov commented
Переключил слияние на мастер

2019-11-13 13:37 UTC, leshiy1295 requested changes
пока особо нечего ревьюить
то, что есть - совершенно непонятно
то, что должно быть - этого нет

2019-11-13 13:37 UTC, leshiy1295 commented on GTest.cpp
> +#include "Presentor.h"
PresentEr

2019-11-13 13:37 UTC, leshiy1295 commented on GTest.cpp
> +    SUCCEED();
таких тестов быть не должно

2019-11-13 13:37 UTC, leshiy1295 commented on GTest.cpp
> +    catch (...) {
про это тоже говорили на РК - такого быть не должно

2019-11-13 13:37 UTC, leshiy1295 commented on GTest.cpp
> +    EXPECT_ANY_THROW(view.testThrow());
expect_any - плохая проверка

2019-11-13 13:37 UTC, leshiy1295 commented on Presentor.cpp
> +#include "headers/Presentor.h"
нет реализации...

2019-11-13 13:37 UTC, leshiy1295 commented on headers/Event.h
> +        std::variant<formatCheckEvent, compressEvent, decompressEvent, archiveEvent, dearchiveEvent, testEvent> data;
обсуждали на РК, что использовать variant для хранения всех типов смысла нет
нужно заменить на ООП подход

2019-11-13 13:37 UTC, leshiy1295 commented on headers/IEventable.h
> +class IEventable {
takeEvent и Eventable - не особо связанные вещи

2019-11-13 13:37 UTC, leshiy1295 commented on headers/ITestable.h
> +    virtual void testThrow() = 0;
почему testThrow и Testable?

2019-11-13 13:37 UTC, leshiy1295 commented on headers/IView.h
> +    virtual void update() = 0; // would be using to update QT interface
это какой-то чрезмерно магический метод, под который сложно что-то конкретное сделать

2019-11-13 13:37 UTC, leshiy1295 commented on headers/Presentor.h
> +    std::set <IEventable*> archiver;
выносить set в интерфейс - плохая идея
если структура данных поменяется, то придётся менять интерфейс => стоит вынести в отдельную сущность, в которой инкапсулировать конкретную низкоуровневую структуру данных
+ здесь раскрыто приватное строение класса => нужно убрать из header, например, с помощью PIMPL

2019-11-13 13:37 UTC, leshiy1295 commented on headers/Presentor.h
> +    void Subscribe(const IEventable* sub, Event::eventType type);
кажется, что Subscribe/Unsubscribe стоило как раз вынести в отдельный интерфейс

2019-11-13 13:37 UTC, leshiy1295 commented on headers/TestSub.h
> +        throw std::invalid_argument{"that's okay"};
???

2019-11-13 13:37 UTC, leshiy1295 commented on headers/View.h
> +      presentor = new Presentor(this);
это не тестируемо, так как сущность создаётся полностью внутри

2019-11-13 13:37 UTC, leshiy1295 commented on headers/View.h
> +
сейчас не реализована основная логика, которая должна была быть выполнена в течение второго модуля - это представление всех экранов/конкретных объектов и событий, которые должны быть на них
сейчас совершенно непонятно, что реализовывать, пока эта задача не выполнена

2019-11-13 13:37 UTC, leshiy1295 commented on main.cpp
> +#include "headers/View.h"
зачем?

и тут пока ничего нет :(

2019-12-07 10:37 UTC, alexey-ershkov commented
Реквест к РК

2019-12-15 11:46 UTC, leshiy1295 requested changes
нужно стремительно всё дорабатывать, потому что времени до предзащиты осталось критически мало, а не сделано ещё многое...

2019-12-15 11:46 UTC, leshiy1295 commented on Archive.cpp
> +        ////Вызов алгоритмов на проверку типа данных
и где же вызов?
+ try-catch-flow не должен использоваться как основной

2019-12-15 11:46 UTC, leshiy1295 commented on GTest.cpp
> +#define log_filename "ArchiverTestLog.txt"
основная директория должна передаваться через CMake/любым другим способом извне

2019-12-15 11:46 UTC, leshiy1295 commented on Presenter.cpp
> +    ////В случае нового вида возврата данных дописать здесь
TODO

2019-12-15 11:46 UTC, leshiy1295 commented on Presenter.cpp
> +            if (response.state == ModelResponse<>::ok) {
else?

2019-12-15 11:46 UTC, leshiy1295 commented on Presenter.cpp
> +                return;
return внутри цикла - плохо

2019-12-15 11:46 UTC, leshiy1295 commented on Show.cpp
> +    std::vector<std::string> fake_filenames = {"File1", "File2", "File3", "File4", "File5"};
заглушка должна быть на уровне сущностей, а не на уровне переменных

2019-12-15 11:46 UTC, leshiy1295 commented on View.cpp
> +    while (select < 1 || select > 2)
магические константы + неговорящее название переменной

2019-12-15 11:46 UTC, leshiy1295 commented on View.cpp
> +    output << shift + "Choose action: \n" + shift +
это должны быть не методы View, а отдельная ConsoleView, или что-то в этом роде... - обсуждали на РК

2019-12-15 11:46 UTC, leshiy1295 commented on View.cpp
> +        input.ignore(32767,'\n'); //
что это?

2019-12-15 11:46 UTC, leshiy1295 commented on headers/Presenter.h
> +    /// в данной реализации хватает работы с ветором строк
комментарий не соответствует реализации

2019-12-15 11:46 UTC, leshiy1295 commented on headers/Presenter.h
> +        auto show  = std::make_shared<Show>();
тоже обсуждали на РК - сейчас всё создаётся внутри и не внедряется извне

2019-12-15 11:46 UTC, leshiy1295 commented on headers/Request.h
> +    std::unordered_multimap <std::string, std::string> types;
в header-файле использовать явно vector/unordered_multimap - плохо - оборачивайте в отдельные структуры

2019-12-15 11:46 UTC, leshiy1295 commented on headers/View.h
> +        return access(filename, 0) != -1;
магические константы

2019-12-15 11:46 UTC, leshiy1295 commented on headers/View.h
> +    void system_clear();
кажется, что методов много для одного класса...
стоит разбить на отдельные сущности

2019-12-15 11:46 UTC, leshiy1295 commented on headers/Presenter.h
> +private:
также на РК обсудили, что должен быть свой Presenter для каждой View...

2019-12-21 03:57 UTC, alexey-ershkov commented
Запрос на ревью. Исправлены замечания и добавлено разделение логики библиотеки и внешнего интерфейса на qt. Разделена сборка библиотеки архиватора  и сборка Qt - интерфейса.

2019-12-28 17:02 UTC, leshiy1295 reviewed
хорошо, что оно всё же завелось, и хоть в каком-то базовом приближении получилось поддержать несколько View, хоть и до полноценного MVP тут, конечно, ещё работать и работать :)

2019-12-28 17:02 UTC, leshiy1295 commented on ArchiverQt/SuccessMessage.qml
> +    Image {
qml, конечно, не плюсы
проверять тут сложно что-то :)
но константы тоже стоило выносить в отдельные ресурсы, чтобы не копировать и не выискивать при рефакторинге их по всем ресурсным файлам...

2019-12-28 17:02 UTC, leshiy1295 commented on ConsoleView.cpp
> +    while (user_input < 1 || user_input > 2)
действительно непонятно, что такое 1 и 2...

2019-12-28 17:02 UTC, leshiy1295 commented on main.cpp
> +        view = new ConsoleView(true);
непонятный интерфейс...

2019-12-28 17:02 UTC, leshiy1295 commented on ConsoleView.cpp
> +        case SHOW:
подобные штуки также можно разносить по функциям при помощи паттерна Visitor, делая обработчики для каждого действия

2019-12-28 17:02 UTC, leshiy1295 commented on lib_headers/View.h
> +class View {
интерфейс показался довольно слишком общим...
по-хорошему, его нужно было конкретизировать, и разбить на разные элементы, которые реально присутствуют, при этом - для каждого экрана отдельно, а не как сейчас...

2019-12-28 17:02 UTC, leshiy1295 commented on lib_headers/Request.h
> +    std::unordered_multimap <std::string, std::string> types;
в .h-файле...
больно

2019-12-29 12:29 UTC, alexey-ershkov commented on lib_headers/Request.h
> +    std::unordered_multimap <std::string, std::string> types;
Лучше в .cpp?

2019-12-29 12:30 UTC, alexey-ershkov commented on ConsoleView.cpp
> +        case SHOW:
Почитаю обязательно

2019-12-29 12:33 UTC, alexey-ershkov commented on lib_headers/View.h
> +class View {
Тогда и Presenter-ы разные сделать стоило, для разных элементов. Тут ведь получилось, что такой класс View работает только с одним видом Presenter. Изначально паттерн был понят неправильно и из-за этого в конце уже поздно было что-то переделывать

2021-01-02 22:00 UTC, merged